import { defineEditorialSource, type EditorialSourceSeed } from "./source-governance.ts";

const ICP = {
  agro: "Agronegócio",
  machines: "Máquinas e Equipamentos Pesados",
  chemical: "Indústria Química",
  plastics: "Termoplásticos",
  steel: "Aço",
  paints: "Tintas",
  animal: "Nutrição Animal",
  acm: "ACM",
} as const;

function source(input: Parameters<typeof defineEditorialSource>[0]): EditorialSourceSeed {
  return defineEditorialSource(input);
}

export const PRIORITY_EDITORIAL_SOURCES: EditorialSourceSeed[] = [
  source({
    sourceKey: "diario-oficial-uniao", name: "Diário Oficial da União", domain: "in.gov.br", baseUrl: "https://www.in.gov.br",
    category: "Governo Federal / Regulação", subcategories: ["legislação", "concessões", "autorizações"], sourceType: "official",
    editorialRole: "regulation", primaryOrSecondary: "primary", officialEntity: true, reliability: 98, priority: 100,
    topicsAllowed: ["portarias", "resoluções", "decretos", "autorizações", "concessões"], relatedIcps: Object.values(ICP),
    preferredOriginalSource: true, capabilities: { regulation: true }, editorialNotes: "Fonte jurídica primária; diferenciar anúncio, autorização, contratação, licitação, início e conclusão.",
  }),
  source({
    sourceKey: "ministerio-transportes", name: "Ministério dos Transportes", domain: "gov.br", baseUrl: "https://www.gov.br/transportes/pt-br",
    category: "Transporte / Infraestrutura",
    subcategories: ["rodovias", "ferrovias", "concessões", "transporte rodoviário de cargas"], sourceType: "official", editorialRole: "confirmation",
    primaryOrSecondary: "primary", officialEntity: true, reliability: 96, priority: 98, topicsAllowed: ["rodovias", "ferrovias", "concessões", "CIOT", "vale-pedágio", "piso mínimo"],
    relatedIcps: [ICP.agro, ICP.machines, ICP.chemical, ICP.plastics, ICP.steel, ICP.paints, ICP.animal, ICP.acm], preferredOriginalSource: true,
    capabilities: { regulation: true, statistics: true, operationalDisruption: true },
  }),
  source({
    sourceKey: "ministerio-portos-aeroportos", name: "Ministério de Portos e Aeroportos", domain: "gov.br", baseUrl: "https://www.gov.br/portos-e-aeroportos/pt-br",
    category: "Portos / Aviação / Cabotagem",
    subcategories: ["portos", "aviação de cargas", "cabotagem"], sourceType: "official", editorialRole: "confirmation", primaryOrSecondary: "primary",
    officialEntity: true, reliability: 96, priority: 97, topicsAllowed: ["portos", "aeroportos", "cabotagem", "concessões"], relatedIcps: Object.values(ICP),
    preferredOriginalSource: true, capabilities: { regulation: true, statistics: true, operationalDisruption: true },
  }),
  source({
    sourceKey: "mapa", name: "Ministério da Agricultura e Pecuária — MAPA", domain: "gov.br", baseUrl: "https://www.gov.br/agricultura/pt-br",
    category: "Agronegócio",
    subcategories: ["produção agropecuária", "sanidade", "insumos", "comércio exterior"], sourceType: "official", editorialRole: "confirmation",
    primaryOrSecondary: "primary", officialEntity: true, reliability: 97, priority: 99, topicsAllowed: ["safra", "sanidade", "fertilizantes", "defensivos", "exportações agropecuárias"],
    relatedIcps: [ICP.agro, ICP.animal, ICP.chemical], preferredOriginalSource: true, capabilities: { regulation: true, statistics: true, operationalDisruption: true, internationalTrade: true },
  }),
  source({
    sourceKey: "mdic", name: "Ministério do Desenvolvimento, Indústria, Comércio e Serviços — MDIC", domain: "gov.br", baseUrl: "https://www.gov.br/mdic/pt-br",
    feedCandidates: ["https://www.gov.br/mdic/pt-br/assuntos/comercio-exterior/estatisticas/informativos/RSS"], category: "Indústria / Comércio Exterior",
    subcategories: ["indústria", "balança comercial", "comércio exterior"], sourceType: "official", editorialRole: "statistics", primaryOrSecondary: "primary",
    officialEntity: true, reliability: 97, priority: 99, topicsAllowed: ["indústria", "exportações", "importações", "balança comercial"], relatedIcps: Object.values(ICP),
    preferredOriginalSource: true, capabilities: { regulation: true, statistics: true, internationalTrade: true },
  }),
  source({
    sourceKey: "ministerio-fazenda", name: "Ministério da Fazenda", domain: "gov.br", baseUrl: "https://www.gov.br/fazenda/pt-br",
    category: "Economia", subcategories: ["política econômica", "tributação", "crédito"],
    sourceType: "official", editorialRole: "confirmation", primaryOrSecondary: "primary", officialEntity: true, reliability: 96, priority: 94,
    topicsAllowed: ["economia", "tributação", "crédito", "política fiscal"], relatedIcps: Object.values(ICP), preferredOriginalSource: true,
    capabilities: { regulation: true, statistics: true },
  }),
  source({
    sourceKey: "ministerio-minas-energia", name: "Ministério de Minas e Energia", domain: "gov.br", baseUrl: "https://www.gov.br/mme/pt-br",
    category: "Energia / Petróleo / Mineração", subcategories: ["energia", "petróleo", "combustíveis", "mineração"],
    sourceType: "official", editorialRole: "confirmation", primaryOrSecondary: "primary", officialEntity: true, reliability: 96, priority: 95,
    topicsAllowed: ["energia", "combustíveis", "mineração", "infraestrutura energética"], relatedIcps: Object.values(ICP), preferredOriginalSource: true,
    capabilities: { regulation: true, statistics: true, operationalDisruption: true, prices: true },
  }),
  source({
    sourceKey: "antt", name: "Agência Nacional de Transportes Terrestres — ANTT", domain: "gov.br", baseUrl: "https://www.gov.br/antt/pt-br",
    category: "Transporte", subcategories: ["rodovias", "ferrovias", "regulação de cargas"],
    sourceType: "regulator", editorialRole: "regulation", primaryOrSecondary: "primary", officialEntity: true, reliability: 98, priority: 100,
    topicsAllowed: ["transporte rodoviário", "ferrovias", "concessões", "frete", "CIOT"], relatedIcps: Object.values(ICP), preferredOriginalSource: true,
    capabilities: { regulation: true, statistics: true, operationalDisruption: true, prices: true },
  }),
  source({
    sourceKey: "antt-legis", name: "ANTT Legis", domain: "anttlegis.antt.gov.br", baseUrl: "https://anttlegis.antt.gov.br",
    category: "Regulação do Transporte", subcategories: ["legislação", "resoluções", "deliberações"], sourceType: "official", editorialRole: "regulation",
    primaryOrSecondary: "primary", officialEntity: true, reliability: 99, priority: 100, topicsAllowed: ["legislação de transportes", "resoluções ANTT"],
    relatedIcps: Object.values(ICP), preferredOriginalSource: true, preferredMonitoringMode: "reference", capabilities: { regulation: true },
  }),
  source({
    sourceKey: "antaq", name: "Agência Nacional de Transportes Aquaviários — ANTAQ", domain: "gov.br", baseUrl: "https://www.gov.br/antaq/pt-br",
    category: "Portos / Transporte Aquaviário", subcategories: ["portos", "navegação", "cabotagem"],
    sourceType: "regulator", editorialRole: "regulation", primaryOrSecondary: "primary", officialEntity: true, reliability: 98, priority: 100,
    topicsAllowed: ["portos", "frete marítimo", "cabotagem", "movimentação portuária"], relatedIcps: Object.values(ICP), preferredOriginalSource: true,
    capabilities: { regulation: true, statistics: true, operationalDisruption: true },
  }),
  source({
    sourceKey: "antaq-paineis", name: "Painéis ANTAQ", domain: "gov.br", baseUrl: "https://www.gov.br/antaq/pt-br/central-de-conteudos/paineis",
    category: "Portos / Dados", subcategories: ["movimentação portuária", "estatísticas aquaviárias"], sourceType: "statistical", editorialRole: "statistics",
    primaryOrSecondary: "primary", officialEntity: true, reliability: 98, priority: 96, topicsAllowed: ["dados portuários", "movimentação de cargas", "cabotagem"],
    relatedIcps: Object.values(ICP), preferredOriginalSource: true, preferredMonitoringMode: "reference", capabilities: { statistics: true },
  }),
  source({
    sourceKey: "anac", name: "Agência Nacional de Aviação Civil — ANAC", domain: "gov.br", baseUrl: "https://www.gov.br/anac/pt-br",
    category: "Aviação", subcategories: ["aviação de cargas", "aeroportos", "regulação aérea"],
    sourceType: "regulator", editorialRole: "regulation", primaryOrSecondary: "primary", officialEntity: true, reliability: 98, priority: 96,
    topicsAllowed: ["aviação de cargas", "aeroportos", "restrições operacionais"], relatedIcps: Object.values(ICP), preferredOriginalSource: true,
    capabilities: { regulation: true, statistics: true, operationalDisruption: true },
  }),
  source({
    sourceKey: "dnit", name: "Departamento Nacional de Infraestrutura de Transportes — DNIT", domain: "gov.br", baseUrl: "https://www.gov.br/dnit/pt-br",
    category: "Rodovias / Infraestrutura", subcategories: ["rodovias", "obras", "interdições"],
    sourceType: "official", editorialRole: "operational_alert", primaryOrSecondary: "primary", officialEntity: true, reliability: 98, priority: 100,
    topicsAllowed: ["obras rodoviárias", "interdições", "infraestrutura federal"], relatedIcps: Object.values(ICP), preferredOriginalSource: true,
    capabilities: { regulation: true, operationalDisruption: true },
  }),
  source({
    sourceKey: "infra-sa", name: "Infra S.A.", domain: "infrasa.gov.br", baseUrl: "https://www.infrasa.gov.br", category: "Infraestrutura / Planejamento",
    subcategories: ["planejamento logístico", "ferrovias", "dados de transporte"], sourceType: "operator", editorialRole: "research", primaryOrSecondary: "primary",
    officialEntity: true, reliability: 92, priority: 91, topicsAllowed: ["planejamento logístico", "infraestrutura", "ferrovias"], relatedIcps: Object.values(ICP),
    preferredOriginalSource: true, capabilities: { statistics: true, companyEvents: true, operationalDisruption: true },
  }),
  source({
    sourceKey: "ibge", name: "Instituto Brasileiro de Geografia e Estatística — IBGE", domain: "ibge.gov.br", baseUrl: "https://www.ibge.gov.br",
    category: "Economia / Estatística", subcategories: ["indústria", "agropecuária", "comércio", "serviços"], sourceType: "statistical", editorialRole: "statistics",
    primaryOrSecondary: "primary", officialEntity: true, reliability: 99, priority: 100, topicsAllowed: ["estatísticas econômicas", "indústria", "agropecuária", "preços"],
    relatedIcps: Object.values(ICP), preferredOriginalSource: true, preferredMonitoringMode: "reference", capabilities: { statistics: true, prices: true },
  }),
  source({
    sourceKey: "agencia-noticias-ibge", name: "Agência de Notícias IBGE", domain: "agenciadenoticias.ibge.gov.br", baseUrl: "https://agenciadenoticias.ibge.gov.br",
    feedCandidates: ["https://agenciadenoticias.ibge.gov.br/agencia-rss"], category: "Economia / Dados", subcategories: ["notícias estatísticas", "releases oficiais"],
    sourceType: "institutional", editorialRole: "statistics", primaryOrSecondary: "primary", officialEntity: true, reliability: 97, priority: 99,
    topicsAllowed: ["indicadores econômicos", "indústria", "agropecuária", "transportes"], relatedIcps: Object.values(ICP), preferredOriginalSource: true,
    capabilities: { statistics: true, prices: true },
  }),
  source({
    sourceKey: "sidra-ibge", name: "SIDRA — IBGE", domain: "sidra.ibge.gov.br", baseUrl: "https://sidra.ibge.gov.br", category: "Dados Estatísticos",
    subcategories: ["séries históricas", "tabelas estatísticas"], sourceType: "statistical", editorialRole: "statistics", primaryOrSecondary: "primary",
    officialEntity: true, reliability: 99, priority: 98, topicsAllowed: ["dados estatísticos", "séries históricas"], relatedIcps: Object.values(ICP),
    preferredOriginalSource: true, preferredMonitoringMode: "reference", capabilities: { statistics: true, prices: true },
  }),
  source({
    sourceKey: "banco-central", name: "Banco Central do Brasil", domain: "bcb.gov.br", baseUrl: "https://www.bcb.gov.br", category: "Economia / Mercado Financeiro",
    subcategories: ["juros", "câmbio", "crédito", "expectativas"], sourceType: "official", editorialRole: "statistics", primaryOrSecondary: "primary",
    officialEntity: true, reliability: 99, priority: 98, topicsAllowed: ["câmbio", "juros", "crédito", "Focus", "inflação"], relatedIcps: Object.values(ICP),
    preferredOriginalSource: true, preferredMonitoringMode: "reference", capabilities: { regulation: true, statistics: true, prices: true },
  }),
  source({
    sourceKey: "ipea", name: "Instituto de Pesquisa Econômica Aplicada — Ipea", domain: "ipea.gov.br", baseUrl: "https://www.ipea.gov.br",
    category: "Economia / Pesquisa", subcategories: ["conjuntura", "infraestrutura", "comércio exterior"],
    sourceType: "research", editorialRole: "research", primaryOrSecondary: "primary", officialEntity: true, reliability: 94, priority: 91,
    topicsAllowed: ["economia", "infraestrutura", "comércio exterior", "transportes"], relatedIcps: Object.values(ICP), preferredOriginalSource: true,
    capabilities: { statistics: true, internationalTrade: true },
  }),
  source({
    sourceKey: "conab", name: "Companhia Nacional de Abastecimento — Conab", domain: "conab.gov.br", baseUrl: "https://www.conab.gov.br",
    category: "Agronegócio / Commodities",
    subcategories: ["safras", "armazenagem", "preços agrícolas"], sourceType: "statistical", editorialRole: "statistics", primaryOrSecondary: "primary",
    officialEntity: true, reliability: 97, priority: 98, topicsAllowed: ["safra", "armazenagem", "commodities", "preços agrícolas"], relatedIcps: [ICP.agro, ICP.animal],
    preferredOriginalSource: true, capabilities: { statistics: true, prices: true },
  }),
  source({
    sourceKey: "embrapa", name: "Empresa Brasileira de Pesquisa Agropecuária — Embrapa", domain: "embrapa.br", baseUrl: "https://www.embrapa.br",
    category: "Agronegócio / Pesquisa", subcategories: ["produção vegetal", "produção animal", "insumos", "florestas"], sourceType: "research",
    editorialRole: "research", primaryOrSecondary: "primary", officialEntity: true, reliability: 95, priority: 92,
    topicsAllowed: ["pesquisa agropecuária", "produção animal", "produção vegetal", "florestas"], relatedIcps: [ICP.agro, ICP.animal, ICP.chemical],
    preferredOriginalSource: true, preferredMonitoringMode: "reference", capabilities: { statistics: true },
  }),
  source({
    sourceKey: "cepea-esalq", name: "Cepea/Esalq-USP", domain: "cepea.esalq.usp.br", baseUrl: "https://www.cepea.esalq.usp.br",
    category: "Agronegócio / Commodities", subcategories: ["indicadores", "preços", "mercados agropecuários"],
    sourceType: "academic", editorialRole: "statistics", primaryOrSecondary: "primary", officialEntity: false, reliability: 94, priority: 94,
    topicsAllowed: ["commodities agrícolas", "preços", "indicadores Cepea"], relatedIcps: [ICP.agro, ICP.animal], preferredOriginalSource: true,
    capabilities: { statistics: true, prices: true }, editorialNotes: "Primária apenas para indicadores produzidos pelo próprio Cepea.",
  }),
  source({
    sourceKey: "comex-stat", name: "Comex Stat", domain: "comexstat.mdic.gov.br", baseUrl: "https://comexstat.mdic.gov.br/pt/home", category: "Comércio Exterior / Dados",
    subcategories: ["exportações", "importações", "balança comercial"], sourceType: "statistical", editorialRole: "statistics", primaryOrSecondary: "primary",
    officialEntity: true, reliability: 99, priority: 100, topicsAllowed: ["exportações", "importações", "comércio exterior"], relatedIcps: Object.values(ICP),
    preferredOriginalSource: true, preferredMonitoringMode: "reference", capabilities: { statistics: true, internationalTrade: true },
  }),
  source({
    sourceKey: "siscomex", name: "Portal Único Siscomex", domain: "gov.br", baseUrl: "https://www.gov.br/siscomex/pt-br",
    category: "Comércio Exterior", subcategories: ["operações aduaneiras", "sistemas", "normas"],
    sourceType: "official", editorialRole: "regulation", primaryOrSecondary: "primary", officialEntity: true, reliability: 98, priority: 98,
    topicsAllowed: ["comércio exterior", "aduana", "exportação", "importação"], relatedIcps: Object.values(ICP), preferredOriginalSource: true,
    capabilities: { regulation: true, operationalDisruption: true, internationalTrade: true },
  }),
  source({
    sourceKey: "receita-federal", name: "Receita Federal", domain: "gov.br", baseUrl: "https://www.gov.br/receitafederal/pt-br",
    feedCandidates: ["https://www.gov.br/receitafederal/pt-br/assuntos/noticias/RSS"], category: "Comércio Exterior / Tributação",
    subcategories: ["aduana", "tributação", "fiscalização"], sourceType: "official", editorialRole: "regulation", primaryOrSecondary: "primary",
    officialEntity: true, reliability: 98, priority: 97, topicsAllowed: ["tributação", "aduana", "comércio exterior"], relatedIcps: Object.values(ICP),
    preferredOriginalSource: true, capabilities: { regulation: true, statistics: true, internationalTrade: true },
  }),
  source({
    sourceKey: "anp", name: "Agência Nacional do Petróleo, Gás Natural e Biocombustíveis — ANP", domain: "gov.br", baseUrl: "https://www.gov.br/anp/pt-br",
    category: "Petróleo / Combustíveis",
    subcategories: ["combustíveis", "preços", "abastecimento"], sourceType: "regulator", editorialRole: "regulation", primaryOrSecondary: "primary",
    officialEntity: true, reliability: 98, priority: 98, topicsAllowed: ["combustíveis", "preços", "abastecimento", "biocombustíveis"], relatedIcps: Object.values(ICP),
    preferredOriginalSource: true, capabilities: { regulation: true, statistics: true, operationalDisruption: true, prices: true },
  }),
  source({
    sourceKey: "epe", name: "Empresa de Pesquisa Energética — EPE", domain: "epe.gov.br", baseUrl: "https://www.epe.gov.br", category: "Energia",
    subcategories: ["planejamento energético", "combustíveis", "eletricidade"], sourceType: "research", editorialRole: "research", primaryOrSecondary: "primary",
    officialEntity: true, reliability: 95, priority: 91, topicsAllowed: ["energia", "combustíveis", "planejamento energético"], relatedIcps: Object.values(ICP),
    preferredOriginalSource: true, preferredMonitoringMode: "reference", capabilities: { statistics: true, prices: true },
  }),
  source({
    sourceKey: "inmet", name: "Instituto Nacional de Meteorologia — Inmet", domain: "portal.inmet.gov.br", baseUrl: "https://portal.inmet.gov.br",
    category: "Meteorologia", subcategories: ["previsão", "alertas", "dados meteorológicos"], sourceType: "official", editorialRole: "operational_alert",
    primaryOrSecondary: "primary", officialEntity: true, reliability: 98, priority: 100, topicsAllowed: ["meteorologia", "chuvas", "seca", "alertas"],
    relatedIcps: [ICP.agro, ICP.animal], preferredOriginalSource: true, preferredMonitoringMode: "reference", capabilities: { operationalDisruption: true, weather: true },
  }),
  source({
    sourceKey: "cemaden", name: "Centro Nacional de Monitoramento e Alertas de Desastres Naturais — Cemaden", domain: "gov.br", baseUrl: "https://www.gov.br/cemaden/pt-br",
    feedCandidates: ["https://www.gov.br/cemaden/pt-br/assuntos/noticias-cemaden/RSS"], category: "Riscos Climáticos", subcategories: ["desastres", "alertas", "riscos hidrológicos"],
    sourceType: "research", editorialRole: "operational_alert", primaryOrSecondary: "primary", officialEntity: true, reliability: 98, priority: 100,
    topicsAllowed: ["desastres naturais", "chuvas", "inundações", "secas"], relatedIcps: Object.values(ICP), preferredOriginalSource: true,
    capabilities: { statistics: true, operationalDisruption: true, weather: true },
  }),
  source({
    sourceKey: "cnt", name: "Confederação Nacional do Transporte — CNT", domain: "cnt.org.br", baseUrl: "https://cnt.org.br",
    category: "Transporte / Logística", subcategories: ["pesquisas de transporte", "rodovias", "custos"],
    sourceType: "association", editorialRole: "research", primaryOrSecondary: "primary", reliability: 88, priority: 87,
    topicsAllowed: ["transporte", "rodovias", "custos logísticos"], relatedIcps: Object.values(ICP), requiresCrossCheck: true, minimumConfirmationSources: 2,
    biasOrInterestDisclosure: "Entidade representativa do setor de transporte; atribuir levantamentos e posições explicitamente à CNT.", capabilities: { statistics: true },
    editorialNotes: "Primária apenas para pesquisas próprias; posições institucionais exigem contexto independente.",
  }),
  source({
    sourceKey: "cni", name: "Confederação Nacional da Indústria — CNI", domain: "portaldaindustria.com.br", baseUrl: "https://www.portaldaindustria.com.br/cni",
    category: "Indústria", subcategories: ["produção industrial", "comércio exterior", "confiança"], sourceType: "association", editorialRole: "research",
    primaryOrSecondary: "primary", reliability: 88, priority: 87, topicsAllowed: ["indústria", "produção", "confiança empresarial", "comércio exterior"],
    relatedIcps: [ICP.machines, ICP.chemical, ICP.plastics, ICP.steel, ICP.paints, ICP.acm], requiresCrossCheck: true, minimumConfirmationSources: 2,
    biasOrInterestDisclosure: "Entidade representativa da indústria; atribuir levantamentos e posições explicitamente à CNI.", capabilities: { statistics: true, internationalTrade: true },
    editorialNotes: "Primária apenas para pesquisas próprias; posições institucionais exigem contexto independente.",
  }),
  source({
    sourceKey: "reuters", name: "Reuters", domain: "reuters.com", baseUrl: "https://www.reuters.com", category: "Agência de Notícias",
    subcategories: ["economia", "commodities", "mercados internacionais"], sourceType: "press", editorialRole: "context", primaryOrSecondary: "secondary",
    authorityProfile: "news_agency", country: "GB", language: "en", reliability: 90, priority: 86, topicsAllowed: ["economia", "commodities", "comércio internacional", "energia"], relatedIcps: Object.values(ICP),
    requiresCrossCheck: true, minimumConfirmationSources: 2, paywall: "partial", geographicScope: "Internacional com impacto no Brasil",
    topicsRestricted: ["notícia internacional sem impacto brasileiro"], editorialNotes: "Não há feed oficial público aprovado no seed; usar como contexto e confirmar com fonte primária.",
  }),
  source({
    sourceKey: "valor-economico", name: "Valor Econômico", domain: "valor.globo.com", baseUrl: "https://valor.globo.com", category: "Economia",
    subcategories: ["empresas", "macroeconomia", "agronegócio"], sourceType: "press", editorialRole: "context", primaryOrSecondary: "secondary", authorityProfile: "economic_outlet",
    reliability: 89, priority: 85, topicsAllowed: ["economia", "empresas", "agronegócio", "comércio exterior"], relatedIcps: Object.values(ICP),
    requiresCrossCheck: true, minimumConfirmationSources: 2, paywall: "partial", requiresJavascript: true,
    editorialNotes: "Veículo econômico secundário; não contornar paywall e confirmar fatos relevantes em fonte primária.",
  }),
  source({
    sourceKey: "unctad", name: "United Nations Conference on Trade and Development — UNCTAD", domain: "unctad.org", baseUrl: "https://unctad.org",
    category: "Comércio / Transporte Marítimo", subcategories: ["comércio internacional", "frete marítimo", "desenvolvimento"],
    sourceType: "international", editorialRole: "research", primaryOrSecondary: "primary", officialEntity: true, country: "UN", language: "en", reliability: 96, priority: 92,
    topicsAllowed: ["comércio internacional", "transporte marítimo", "fretes", "cadeias globais"], relatedIcps: Object.values(ICP), geographicScope: "Internacional com impacto no Brasil",
    preferredOriginalSource: true, capabilities: { statistics: true, internationalTrade: true },
  }),
  source({
    sourceKey: "usda-fas", name: "USDA Foreign Agricultural Service", domain: "fas.usda.gov", baseUrl: "https://www.fas.usda.gov/data",
    category: "Commodities Agrícolas", subcategories: ["produção agrícola", "comércio agrícola", "mercados globais"],
    sourceType: "official", editorialRole: "statistics", primaryOrSecondary: "primary", officialEntity: true, country: "US", language: "en", reliability: 97, priority: 94,
    topicsAllowed: ["commodities agrícolas", "produção mundial", "exportações", "importações"], relatedIcps: [ICP.agro, ICP.animal], geographicScope: "Internacional com impacto no Brasil",
    preferredOriginalSource: true, capabilities: { statistics: true, internationalTrade: true },
  }),
];

if (PRIORITY_EDITORIAL_SOURCES.length !== 35) {
  throw new Error(`A whitelist prioritária precisa conter 35 fontes; recebeu ${PRIORITY_EDITORIAL_SOURCES.length}.`);
}
