import {
  boolean,
  doublePrecision,
  index,
  integer,
  pgTable,
  serial,
  text,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const sources = pgTable("sources", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  domain: text("domain").notNull(),
  feedUrl: text("feed_url").notNull().unique(),
  websiteUrl: text("website_url"),
  reliabilityScore: integer("reliability_score").notNull().default(75),
  active: boolean("active").notNull().default(true),
  type: text("type").notNull().default("rss"),
  status: text("status").notNull().default("active"),
  priority: integer("priority").notNull().default(50),
  collectionFrequencyMinutes: integer("collection_frequency_minutes").notNull().default(720),
  language: text("language").notNull().default("pt-BR"),
  country: text("country").notNull().default("BR"),
  region: text("region").notNull().default("Brasil"),
  relatedIcps: text("related_icps").notNull().default("[]"),
  notes: text("notes").notNull().default(""),
  lastCollectedAt: text("last_collected_at"),
  lastSuccessAt: text("last_success_at"),
  lastFailureAt: text("last_failure_at"),
  lastError: text("last_error"),
  lastStatus: text("last_status").notNull().default("never"),
  lastDurationMs: integer("last_duration_ms"),
  lastHttpStatus: integer("last_http_status"),
  lastItemCount: integer("last_item_count").notNull().default(0),
  consecutiveFailures: integer("consecutive_failures").notNull().default(0),
  nextCollectionAt: text("next_collection_at"),
  archivedAt: text("archived_at"),
  totalNewsCollected: integer("total_news_collected").notNull().default(0),
  averageResponseMs: integer("average_response_ms").notNull().default(0),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at"),
});

export const editorialSources = pgTable("editorial_sources", {
  id: serial("id").primaryKey(),
  operationalSourceId: integer("operational_source_id").references(() => sources.id),
  sourceKey: text("source_key").notNull(),
  name: text("name").notNull(),
  domain: text("domain").notNull(),
  baseUrl: text("base_url").notNull(),
  feedUrl: text("feed_url"),
  category: text("category").notNull(),
  subcategories: text("subcategories").notNull().default("[]"),
  authorityLevel: text("authority_level").notNull(),
  authorityScore: integer("authority_score").notNull().default(50),
  sourceType: text("source_type").notNull(),
  editorialRole: text("editorial_role").notNull(),
  primaryOrSecondary: text("primary_or_secondary").notNull(),
  officialEntity: boolean("official_entity").notNull().default(false),
  country: text("country").notNull().default("BR"),
  language: text("language").notNull().default("pt-BR"),
  monitoringMode: text("monitoring_mode").notNull().default("reference"),
  activeForCollection: boolean("active_for_collection").notNull().default(false),
  status: text("status").notNull().default("pending_review"),
  reliability: integer("reliability").notNull().default(75),
  priority: integer("priority").notNull().default(50),
  updateFrequencyMinutes: integer("update_frequency_minutes").notNull().default(720),
  topicsAllowed: text("topics_allowed").notNull().default("[]"),
  topicsRestricted: text("topics_restricted").notNull().default("[]"),
  geographicScope: text("geographic_scope").notNull().default("Brasil"),
  relatedIcps: text("related_icps").notNull().default("[]"),
  requiresCrossCheck: boolean("requires_cross_check").notNull().default(false),
  preferredOriginalSource: boolean("preferred_original_source").notNull().default(false),
  paywall: text("paywall").notNull().default("none"),
  requiresJavascript: boolean("requires_javascript").notNull().default(false),
  robotsStatus: text("robots_status").notNull().default("unknown"),
  sitemapUrl: text("sitemap_url"),
  lastVerifiedAt: text("last_verified_at"),
  lastSuccessfulCollectionAt: text("last_successful_collection_at"),
  lastFailedCollectionAt: text("last_failed_collection_at"),
  consecutiveFailures: integer("consecutive_failures").notNull().default(0),
  editorialNotes: text("editorial_notes").notNull().default(""),
  biasOrInterestDisclosure: text("bias_or_interest_disclosure").notNull().default(""),
  minimumConfirmationSources: integer("minimum_confirmation_sources").notNull().default(1),
  canConfirmRegulation: boolean("can_confirm_regulation").notNull().default(false),
  canConfirmStatistics: boolean("can_confirm_statistics").notNull().default(false),
  canConfirmCompanyEvents: boolean("can_confirm_company_events").notNull().default(false),
  canConfirmOperationalDisruption: boolean("can_confirm_operational_disruption").notNull().default(false),
  canConfirmPrices: boolean("can_confirm_prices").notNull().default(false),
  canConfirmWeather: boolean("can_confirm_weather").notNull().default(false),
  canConfirmInternationalTrade: boolean("can_confirm_international_trade").notNull().default(false),
  archivedAt: text("archived_at"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("editorial_sources_key_unique").on(table.sourceKey),
  index("editorial_sources_domain_idx").on(table.domain),
  index("editorial_sources_collection_idx").on(table.activeForCollection, table.monitoringMode, table.status),
  index("editorial_sources_authority_idx").on(table.authorityLevel, table.authorityScore),
  index("editorial_sources_category_idx").on(table.category, table.country),
  index("editorial_sources_operational_idx").on(table.operationalSourceId),
]);

export const newsItems = pgTable("news_items", {
  id: serial("id").primaryKey(),
  externalId: text("external_id").notNull(),
  title: text("title").notNull(),
  originalUrl: text("original_url").notNull(),
  canonicalUrl: text("canonical_url").notNull(),
  sourceId: integer("source_id").notNull().references(() => sources.id),
  sourceName: text("source_name").notNull(),
  author: text("author"),
  publishedAt: text("published_at").notNull(),
  collectedAt: text("collected_at").notNull(),
  excerpt: text("excerpt").notNull(),
  contentText: text("content_text").notNull().default(""),
  contentHash: text("content_hash").notNull(),
  titleHash: text("title_hash").notNull(),
  region: text("region").notNull(),
  logisticsImpact: text("logistics_impact").notNull(),
  relevanceScore: integer("relevance_score").notNull(),
  status: text("status").notNull().default("new"),
  topics: text("topics").notNull(),
  icps: text("icps").notNull(),
  primaryIcp: text("primary_icp").notNull().default("Mercado e Logística"),
  secondaryIcps: text("secondary_icps").notNull().default("[]"),
  classificationReason: text("classification_reason").notNull(),
  classificationMethod: text("classification_method").notNull().default("deterministic"),
  manuallyEditedAt: text("manually_edited_at"),
  readAt: text("read_at"),
  favorite: boolean("favorite").notNull().default(false),
  archivedAt: text("archived_at"),
  internalNotes: text("internal_notes").notNull().default(""),
  manualOverride: boolean("manual_override").notNull().default(false),
  collectionRunId: text("collection_run_id"),
  updatedAt: text("updated_at"),
}, (table) => [
  uniqueIndex("news_canonical_unique").on(table.canonicalUrl),
  uniqueIndex("news_external_source_unique").on(table.externalId, table.sourceId),
  uniqueIndex("news_title_hash_unique").on(table.titleHash),
  index("news_relevance_idx").on(table.relevanceScore, table.publishedAt),
  index("news_status_idx").on(table.status, table.collectedAt),
  index("news_collection_run_idx").on(table.collectionRunId),
  index("news_published_idx").on(table.publishedAt),
  index("news_primary_icp_published_idx").on(table.primaryIcp, table.publishedAt),
  index("news_source_published_idx").on(table.sourceId, table.publishedAt),
  index("news_status_published_idx").on(table.status, table.publishedAt),
  index("news_archived_published_idx").on(table.archivedAt, table.publishedAt),
  index("news_updated_idx").on(table.updatedAt),
]);

export const newsItemHistory = pgTable("news_item_history", {
  id: serial("id").primaryKey(),
  newsItemId: integer("news_item_id").notNull().references(() => newsItems.id),
  action: text("action").notNull(),
  previousValue: text("previous_value"),
  nextValue: text("next_value"),
  metadata: text("metadata"),
  createdAt: text("created_at").notNull(),
}, (table) => [index("news_history_item_idx").on(table.newsItemId, table.createdAt)]);

export const editorialBriefs = pgTable("editorial_briefs", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  selectedIcp: text("selected_icp").notNull(),
  objective: text("objective").notNull(),
  primaryKeyword: text("primary_keyword").notNull(),
  payload: text("payload").notNull(),
  newsIds: text("news_ids").notNull(),
  status: text("status").notNull().default("draft"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const articles = pgTable("articles", {
  id: serial("id").primaryKey(),
  briefId: integer("brief_id").notNull().references(() => editorialBriefs.id),
  title: text("title").notNull(),
  slug: text("slug").notNull().unique(),
  excerpt: text("excerpt").notNull(),
  content: text("content").notNull(),
  metaTitle: text("meta_title").notNull(),
  metaDescription: text("meta_description").notNull(),
  primaryKeyword: text("primary_keyword").notNull(),
  secondaryKeywords: text("secondary_keywords").notNull(),
  category: text("category").notNull(),
  tags: text("tags").notNull(),
  status: text("status").notNull().default("draft"),
  qualityScore: integer("quality_score").notNull().default(78),
  factualConfidence: doublePrecision("factual_confidence").notNull().default(.8),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const editorialKits = pgTable("editorial_kits", {
  id: serial("id").primaryKey(),
  newsItemId: integer("news_item_id").notNull().references(() => newsItems.id),
  title: text("title").notNull(),
  primaryIcp: text("primary_icp").notNull(),
  editorialScore: integer("editorial_score").notNull(),
  provider: text("provider").notNull(),
  model: text("model").notNull(),
  payload: text("payload").notNull(),
  status: text("status").notNull().default("draft"),
  archivedAt: text("archived_at"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("editorial_kits_news_idx").on(table.newsItemId, table.createdAt),
  index("editorial_kits_status_idx").on(table.status, table.updatedAt),
]);

export const editorialQueue = pgTable("editorial_queue", {
  id: serial("id").primaryKey(),
  newsItemId: integer("news_item_id").notNull().references(() => newsItems.id),
  editorialKitId: integer("editorial_kit_id").references(() => editorialKits.id),
  title: text("title").notNull(),
  status: text("status").notNull().default("new"),
  origin: text("origin").notNull().default("monitoring"),
  version: integer("version").notNull().default(1),
  requestedBy: text("requested_by"),
  lastError: text("last_error"),
  startedAt: text("started_at"),
  completedAt: text("completed_at"),
  archivedAt: text("archived_at"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("editorial_queue_news_version_unique").on(table.newsItemId, table.version),
  uniqueIndex("editorial_queue_active_news_unique").on(table.newsItemId)
    .where(sql`${table.status} in ('new', 'analysis', 'approved', 'generating') and ${table.archivedAt} is null`),
  index("editorial_queue_status_idx").on(table.status, table.updatedAt),
  index("editorial_queue_news_idx").on(table.newsItemId, table.createdAt),
  index("editorial_queue_kit_idx").on(table.editorialKitId),
]);

export const editorialKitSources = pgTable("editorial_kit_sources", {
  id: serial("id").primaryKey(),
  editorialKitId: integer("editorial_kit_id").notNull().references(() => editorialKits.id),
  editorialSourceId: integer("editorial_source_id").references(() => editorialSources.id),
  title: text("title").notNull(),
  url: text("url").notNull(),
  publisher: text("publisher").notNull(),
  primaryOrSecondary: text("primary_or_secondary").notNull(),
  authorityLevel: text("authority_level").notNull(),
  publishedAt: text("published_at"),
  createdAt: text("created_at").notNull(),
}, (table) => [
  uniqueIndex("editorial_kit_sources_url_unique").on(table.editorialKitId, table.url),
  index("editorial_kit_sources_kit_idx").on(table.editorialKitId),
  index("editorial_kit_sources_source_idx").on(table.editorialSourceId),
]);

export const strategicAccounts = pgTable("strategic_accounts", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  aliases: text("aliases").notNull().default("[]"),
  domain: text("domain").notNull(),
  icp: text("icp").notNull(),
  status: text("status").notNull().default("inactive"),
  editorialWeight: integer("editorial_weight").notNull().default(20),
  evidenceSourceUrl: text("evidence_source_url"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("strategic_accounts_domain_unique").on(table.domain),
  index("strategic_accounts_status_idx").on(table.status, table.icp),
]);

export const wordpressPublications = pgTable("wordpress_publications", {
  id: serial("id").primaryKey(),
  articleId: integer("article_id").notNull().unique().references(() => articles.id),
  wordpressPostId: integer("wordpress_post_id").notNull(),
  wordpressUrl: text("wordpress_url"),
  wordpressEditUrl: text("wordpress_edit_url"),
  wordpressStatus: text("wordpress_status").notNull(),
  createdAt: text("created_at").notNull(),
});

export const jobLogs = pgTable("job_logs", {
  id: serial("id").primaryKey(),
  jobType: text("job_type").notNull(),
  status: text("status").notNull(),
  startedAt: text("started_at").notNull(),
  finishedAt: text("finished_at"),
  processedItems: integer("processed_items").notNull().default(0),
  errorMessage: text("error_message"),
  metadata: text("metadata"),
});

export const aiUsageLogs = pgTable("ai_usage_logs", {
  id: serial("id").primaryKey(),
  operation: text("operation").notNull(),
  provider: text("provider").notNull(),
  model: text("model").notNull(),
  status: text("status").notNull(),
  inputTokens: integer("input_tokens").notNull().default(0),
  outputTokens: integer("output_tokens").notNull().default(0),
  estimatedCostUsd: doublePrecision("estimated_cost_usd").notNull().default(0),
  latencyMs: integer("latency_ms").notNull().default(0),
  requestId: text("request_id"),
  errorMessage: text("error_message"),
  createdAt: text("created_at").notNull(),
}, (table) => [index("ai_usage_created_idx").on(table.createdAt)]);

export const jobLocks = pgTable("job_locks", {
  name: text("name").primaryKey(),
  owner: text("owner").notNull(),
  lockedUntil: text("locked_until").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const seoSites = pgTable("seo_sites", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  domain: text("domain").notNull(),
  blogUrl: text("blog_url").notNull(),
  wordpressApiUrl: text("wordpress_api_url"),
  sitemapUrl: text("sitemap_url"),
  rssUrl: text("rss_url"),
  status: text("status").notNull().default("pending_sync"),
  lastSyncAt: text("last_sync_at"),
  nextSyncAt: text("next_sync_at"),
  lastError: text("last_error"),
  articlesFound: integer("articles_found").notNull().default(0),
  articlesSynced: integer("articles_synced").notNull().default(0),
  discoveryMethod: text("discovery_method").notNull().default("wordpress_rest"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("seo_sites_domain_unique").on(table.domain),
  index("seo_sites_status_idx").on(table.status, table.nextSyncAt),
]);

export const seoSiteSources = pgTable("seo_site_sources", {
  id: serial("id").primaryKey(),
  siteId: integer("site_id").notNull().references(() => seoSites.id),
  sourceType: text("source_type").notNull(),
  url: text("url").notNull(),
  status: text("status").notNull().default("active"),
  priority: integer("priority").notNull().default(50),
  lastVerifiedAt: text("last_verified_at"),
  lastError: text("last_error"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("seo_site_sources_url_unique").on(table.siteId, table.url),
  index("seo_site_sources_priority_idx").on(table.siteId, table.status, table.priority),
]);

export const seoArticles = pgTable("seo_articles", {
  id: serial("id").primaryKey(),
  siteId: integer("site_id").notNull().references(() => seoSites.id),
  externalId: text("external_id").notNull(),
  title: text("title").notNull(),
  url: text("url").notNull(),
  canonicalUrl: text("canonical_url").notNull(),
  slug: text("slug").notNull(),
  excerpt: text("excerpt").notNull().default(""),
  contentText: text("content_text").notNull().default(""),
  publishedAt: text("published_at"),
  modifiedAt: text("modified_at"),
  author: text("author"),
  categories: text("categories").notNull().default("[]"),
  tags: text("tags").notNull().default("[]"),
  featuredImageUrl: text("featured_image_url"),
  status: text("status").notNull().default("published"),
  metaDescription: text("meta_description"),
  keywords: text("keywords").notNull().default("[]"),
  icps: text("icps").notNull().default("[]"),
  topics: text("topics").notNull().default("[]"),
  collectionMethod: text("collection_method").notNull(),
  contentHash: text("content_hash").notNull(),
  firstCollectedAt: text("first_collected_at").notNull(),
  lastCollectedAt: text("last_collected_at").notNull(),
  unavailableAt: text("unavailable_at"),
}, (table) => [
  uniqueIndex("seo_articles_external_unique").on(table.siteId, table.externalId),
  uniqueIndex("seo_articles_canonical_unique").on(table.siteId, table.canonicalUrl),
  index("seo_articles_published_idx").on(table.siteId, table.status, table.publishedAt),
  index("seo_articles_hash_idx").on(table.siteId, table.contentHash),
]);

export const seoCompetitors = pgTable("seo_competitors", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  domain: text("domain").notNull(),
  contentUrl: text("content_url"),
  sitemapUrl: text("sitemap_url"),
  rssUrl: text("rss_url"),
  active: boolean("active").notNull().default(true),
  notes: text("notes").notNull().default(""),
  lastSyncAt: text("last_sync_at"),
  syncStatus: text("sync_status").notNull().default("pending_confirmation"),
  lastError: text("last_error"),
  discoveredAt: text("discovered_at"),
  archivedAt: text("archived_at"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("seo_competitors_domain_unique").on(table.domain),
  index("seo_competitors_status_idx").on(table.active, table.syncStatus, table.lastSyncAt),
]);

export const seoCompetitorSources = pgTable("seo_competitor_sources", {
  id: serial("id").primaryKey(),
  competitorId: integer("competitor_id").notNull().references(() => seoCompetitors.id),
  sourceType: text("source_type").notNull(),
  url: text("url").notNull(),
  status: text("status").notNull().default("confirmed"),
  priority: integer("priority").notNull().default(50),
  lastVerifiedAt: text("last_verified_at"),
  lastError: text("last_error"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("seo_competitor_sources_url_unique").on(table.competitorId, table.url),
  index("seo_competitor_sources_priority_idx").on(table.competitorId, table.status, table.priority),
]);

export const seoCompetitorArticles = pgTable("seo_competitor_articles", {
  id: serial("id").primaryKey(),
  competitorId: integer("competitor_id").notNull().references(() => seoCompetitors.id),
  sourceId: integer("source_id").references(() => seoCompetitorSources.id),
  externalId: text("external_id").notNull(),
  title: text("title").notNull(),
  url: text("url").notNull(),
  canonicalUrl: text("canonical_url").notNull(),
  publishedAt: text("published_at"),
  modifiedAt: text("modified_at"),
  excerpt: text("excerpt").notNull().default(""),
  contentText: text("content_text").notNull().default(""),
  featuredImageUrl: text("featured_image_url"),
  categories: text("categories").notNull().default("[]"),
  tags: text("tags").notNull().default("[]"),
  topics: text("topics").notNull().default("[]"),
  contentHash: text("content_hash").notNull(),
  firstCollectedAt: text("first_collected_at").notNull(),
  lastCollectedAt: text("last_collected_at").notNull(),
  status: text("status").notNull().default("published"),
  collectionMethod: text("collection_method").notNull(),
  unavailableAt: text("unavailable_at"),
}, (table) => [
  uniqueIndex("seo_competitor_articles_external_unique").on(table.competitorId, table.externalId),
  uniqueIndex("seo_competitor_articles_canonical_unique").on(table.competitorId, table.canonicalUrl),
  index("seo_competitor_articles_published_idx").on(table.competitorId, table.status, table.publishedAt),
  index("seo_competitor_articles_hash_idx").on(table.competitorId, table.contentHash),
]);

export const seoSyncRuns = pgTable("seo_sync_runs", {
  id: serial("id").primaryKey(),
  scope: text("scope").notNull(),
  targetId: integer("target_id"),
  trigger: text("trigger").notNull(),
  status: text("status").notNull(),
  method: text("method"),
  startedAt: text("started_at").notNull(),
  finishedAt: text("finished_at"),
  durationMs: integer("duration_ms"),
  found: integer("found").notNull().default(0),
  inserted: integer("inserted").notNull().default(0),
  updated: integer("updated").notNull().default(0),
  ignored: integer("ignored").notNull().default(0),
  unavailable: integer("unavailable").notNull().default(0),
  errors: integer("errors").notNull().default(0),
  errorMessage: text("error_message"),
  metadata: text("metadata").notNull().default("{}"),
}, (table) => [
  index("seo_sync_runs_target_idx").on(table.scope, table.targetId, table.startedAt),
  index("seo_sync_runs_status_idx").on(table.status, table.startedAt),
]);

export const seoAuthoritySnapshots = pgTable("seo_authority_snapshots", {
  id: serial("id").primaryKey(),
  siteId: integer("site_id").notNull().references(() => seoSites.id),
  score: integer("score").notNull(),
  previousScore: integer("previous_score"),
  confidence: doublePrecision("confidence").notNull(),
  googleStatus: text("google_status").notNull().default("not_connected"),
  googleScore: integer("google_score"),
  geminiScore: integer("gemini_score"),
  engineScore: integer("engine_score").notNull(),
  contributions: text("contributions").notNull(),
  positiveFactors: text("positive_factors").notNull().default("[]"),
  negativeFactors: text("negative_factors").notNull().default("[]"),
  metrics: text("metrics").notNull(),
  sourceStates: text("source_states").notNull(),
  calculatedAt: text("calculated_at").notNull(),
}, (table) => [
  index("seo_authority_site_idx").on(table.siteId, table.calculatedAt),
]);

export const seoAiAnalyses = pgTable("seo_ai_analyses", {
  id: serial("id").primaryKey(),
  siteId: integer("site_id").references(() => seoSites.id),
  competitorId: integer("competitor_id").references(() => seoCompetitors.id),
  operation: text("operation").notNull(),
  inputHash: text("input_hash").notNull(),
  version: text("version").notNull(),
  provider: text("provider").notNull(),
  model: text("model").notNull(),
  status: text("status").notNull(),
  confidence: doublePrecision("confidence"),
  payload: text("payload").notNull().default("{}"),
  dataRefs: text("data_refs").notNull().default("{}"),
  inputTokens: integer("input_tokens").notNull().default(0),
  outputTokens: integer("output_tokens").notNull().default(0),
  estimatedCostUsd: doublePrecision("estimated_cost_usd").notNull().default(0),
  requestId: text("request_id"),
  errorMessage: text("error_message"),
  validUntil: text("valid_until"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("seo_ai_analyses_input_unique").on(table.operation, table.inputHash),
  index("seo_ai_analyses_site_idx").on(table.siteId, table.operation, table.createdAt),
  index("seo_ai_analyses_competitor_idx").on(table.competitorId, table.operation, table.createdAt),
]);

export const seoOpportunities = pgTable("seo_opportunities", {
  id: serial("id").primaryKey(),
  siteId: integer("site_id").notNull().references(() => seoSites.id),
  opportunityKey: text("opportunity_key").notNull(),
  title: text("title").notNull(),
  topic: text("topic").notNull(),
  icp: text("icp").notNull(),
  priority: text("priority").notNull(),
  seoPotential: text("seo_potential").notNull(),
  confidence: integer("confidence").notNull(),
  reasons: text("reasons").notNull(),
  signalOrigins: text("signal_origins").notNull(),
  competitorIds: text("competitor_ids").notNull().default("[]"),
  newsIds: text("news_ids").notNull().default("[]"),
  siteArticleIds: text("site_article_ids").notNull().default("[]"),
  suggestedAngle: text("suggested_angle"),
  status: text("status").notNull().default("new"),
  validUntil: text("valid_until").notNull(),
  sourceAnalysisId: integer("source_analysis_id").references(() => seoAiAnalyses.id),
  editorialQueueId: integer("editorial_queue_id").references(() => editorialQueue.id),
  editorialKitId: integer("editorial_kit_id").references(() => editorialKits.id),
  reviewedAt: text("reviewed_at"),
  discardedAt: text("discarded_at"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  uniqueIndex("seo_opportunities_key_unique").on(table.siteId, table.opportunityKey),
  index("seo_opportunities_status_idx").on(table.siteId, table.status, table.validUntil),
  index("seo_opportunities_rank_idx").on(table.siteId, table.priority, table.confidence),
  index("seo_opportunities_queue_idx").on(table.editorialQueueId),
  index("seo_opportunities_kit_idx").on(table.editorialKitId),
]);
