import {
  boolean,
  doublePrecision,
  index,
  integer,
  pgTable,
  serial,
  text,
  uniqueIndex,
} from "drizzle-orm/pg-core";

export const sources = pgTable("sources", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  domain: text("domain").notNull(),
  feedUrl: text("feed_url").notNull().unique(),
  websiteUrl: text("website_url"),
  reliabilityScore: integer("reliability_score").notNull().default(75),
  active: boolean("active").notNull().default(true),
  type: text("type").notNull().default("rss"),
  status: text("status").notNull().default("active"),
  priority: integer("priority").notNull().default(50),
  collectionFrequencyMinutes: integer("collection_frequency_minutes").notNull().default(720),
  language: text("language").notNull().default("pt-BR"),
  country: text("country").notNull().default("BR"),
  region: text("region").notNull().default("Brasil"),
  relatedIcps: text("related_icps").notNull().default("[]"),
  notes: text("notes").notNull().default(""),
  lastCollectedAt: text("last_collected_at"),
  lastSuccessAt: text("last_success_at"),
  lastFailureAt: text("last_failure_at"),
  lastError: text("last_error"),
  lastStatus: text("last_status").notNull().default("never"),
  lastDurationMs: integer("last_duration_ms"),
  lastHttpStatus: integer("last_http_status"),
  lastItemCount: integer("last_item_count").notNull().default(0),
  consecutiveFailures: integer("consecutive_failures").notNull().default(0),
  nextCollectionAt: text("next_collection_at"),
  archivedAt: text("archived_at"),
  totalNewsCollected: integer("total_news_collected").notNull().default(0),
  averageResponseMs: integer("average_response_ms").notNull().default(0),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at"),
});

export const newsItems = pgTable("news_items", {
  id: serial("id").primaryKey(),
  externalId: text("external_id").notNull(),
  title: text("title").notNull(),
  originalUrl: text("original_url").notNull(),
  canonicalUrl: text("canonical_url").notNull(),
  sourceId: integer("source_id").notNull().references(() => sources.id),
  sourceName: text("source_name").notNull(),
  author: text("author"),
  publishedAt: text("published_at").notNull(),
  collectedAt: text("collected_at").notNull(),
  excerpt: text("excerpt").notNull(),
  contentText: text("content_text").notNull().default(""),
  contentHash: text("content_hash").notNull(),
  titleHash: text("title_hash").notNull(),
  region: text("region").notNull(),
  logisticsImpact: text("logistics_impact").notNull(),
  relevanceScore: integer("relevance_score").notNull(),
  status: text("status").notNull().default("new"),
  topics: text("topics").notNull(),
  icps: text("icps").notNull(),
  primaryIcp: text("primary_icp").notNull().default("Mercado e Logística"),
  secondaryIcps: text("secondary_icps").notNull().default("[]"),
  classificationReason: text("classification_reason").notNull(),
  classificationMethod: text("classification_method").notNull().default("deterministic"),
  manuallyEditedAt: text("manually_edited_at"),
  readAt: text("read_at"),
  favorite: boolean("favorite").notNull().default(false),
  archivedAt: text("archived_at"),
  internalNotes: text("internal_notes").notNull().default(""),
  manualOverride: boolean("manual_override").notNull().default(false),
  collectionRunId: text("collection_run_id"),
  updatedAt: text("updated_at"),
}, (table) => [
  uniqueIndex("news_canonical_unique").on(table.canonicalUrl),
  uniqueIndex("news_external_source_unique").on(table.externalId, table.sourceId),
  uniqueIndex("news_title_hash_unique").on(table.titleHash),
  index("news_relevance_idx").on(table.relevanceScore, table.publishedAt),
  index("news_status_idx").on(table.status, table.collectedAt),
  index("news_collection_run_idx").on(table.collectionRunId),
]);

export const newsItemHistory = pgTable("news_item_history", {
  id: serial("id").primaryKey(),
  newsItemId: integer("news_item_id").notNull().references(() => newsItems.id),
  action: text("action").notNull(),
  previousValue: text("previous_value"),
  nextValue: text("next_value"),
  metadata: text("metadata"),
  createdAt: text("created_at").notNull(),
}, (table) => [index("news_history_item_idx").on(table.newsItemId, table.createdAt)]);

export const editorialBriefs = pgTable("editorial_briefs", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  selectedIcp: text("selected_icp").notNull(),
  objective: text("objective").notNull(),
  primaryKeyword: text("primary_keyword").notNull(),
  payload: text("payload").notNull(),
  newsIds: text("news_ids").notNull(),
  status: text("status").notNull().default("draft"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const articles = pgTable("articles", {
  id: serial("id").primaryKey(),
  briefId: integer("brief_id").notNull().references(() => editorialBriefs.id),
  title: text("title").notNull(),
  slug: text("slug").notNull().unique(),
  excerpt: text("excerpt").notNull(),
  content: text("content").notNull(),
  metaTitle: text("meta_title").notNull(),
  metaDescription: text("meta_description").notNull(),
  primaryKeyword: text("primary_keyword").notNull(),
  secondaryKeywords: text("secondary_keywords").notNull(),
  category: text("category").notNull(),
  tags: text("tags").notNull(),
  status: text("status").notNull().default("draft"),
  qualityScore: integer("quality_score").notNull().default(78),
  factualConfidence: doublePrecision("factual_confidence").notNull().default(.8),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

export const editorialKits = pgTable("editorial_kits", {
  id: serial("id").primaryKey(),
  newsItemId: integer("news_item_id").notNull().references(() => newsItems.id),
  title: text("title").notNull(),
  primaryIcp: text("primary_icp").notNull(),
  editorialScore: integer("editorial_score").notNull(),
  provider: text("provider").notNull(),
  model: text("model").notNull(),
  payload: text("payload").notNull(),
  status: text("status").notNull().default("draft"),
  archivedAt: text("archived_at"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  index("editorial_kits_news_idx").on(table.newsItemId, table.createdAt),
  index("editorial_kits_status_idx").on(table.status, table.updatedAt),
]);

export const wordpressPublications = pgTable("wordpress_publications", {
  id: serial("id").primaryKey(),
  articleId: integer("article_id").notNull().unique().references(() => articles.id),
  wordpressPostId: integer("wordpress_post_id").notNull(),
  wordpressUrl: text("wordpress_url"),
  wordpressEditUrl: text("wordpress_edit_url"),
  wordpressStatus: text("wordpress_status").notNull(),
  createdAt: text("created_at").notNull(),
});

export const jobLogs = pgTable("job_logs", {
  id: serial("id").primaryKey(),
  jobType: text("job_type").notNull(),
  status: text("status").notNull(),
  startedAt: text("started_at").notNull(),
  finishedAt: text("finished_at"),
  processedItems: integer("processed_items").notNull().default(0),
  errorMessage: text("error_message"),
  metadata: text("metadata"),
});

export const aiUsageLogs = pgTable("ai_usage_logs", {
  id: serial("id").primaryKey(),
  operation: text("operation").notNull(),
  provider: text("provider").notNull(),
  model: text("model").notNull(),
  status: text("status").notNull(),
  inputTokens: integer("input_tokens").notNull().default(0),
  outputTokens: integer("output_tokens").notNull().default(0),
  estimatedCostUsd: doublePrecision("estimated_cost_usd").notNull().default(0),
  latencyMs: integer("latency_ms").notNull().default(0),
  requestId: text("request_id"),
  errorMessage: text("error_message"),
  createdAt: text("created_at").notNull(),
}, (table) => [index("ai_usage_created_idx").on(table.createdAt)]);

export const jobLocks = pgTable("job_locks", {
  name: text("name").primaryKey(),
  owner: text("owner").notNull(),
  lockedUntil: text("locked_until").notNull(),
  updatedAt: text("updated_at").notNull(),
});
